/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/build-plugins.ts
 * 
 * This file contains all CSS and font assets required by installed plugins.
 */

import React from 'react'

// CSS assets from plugins
const CSS_ASSETS: string[] = [
  "https://unpkg.com/tabulator-tables@6.3.1/dist/css/tabulator.min.css",
  "https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.19/main.min.css",
  "https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@6.1.19/main.min.css",
  "https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@6.1.19/main.min.css"
]

// Font assets from plugins
const FONT_ASSETS: string[] = [
  "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
]

/**
 * Component that injects all plugin CSS and font assets
 * Include this in your app's root component
 */
export const PluginAssets: React.FC = () => {
  return (
    <>
      {/* Font preconnects */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      
      {/* Font assets */}
      {FONT_ASSETS.map((font, index) => (
        <link key={`font-${index}`} href={font} rel="stylesheet" />
      ))}
      
      {/* CSS assets */}
      {CSS_ASSETS.map((css, index) => (
        <link key={`css-${index}`} rel="stylesheet" href={css} />
      ))}
    </>
  )
}

// Export asset lists for programmatic access
export const pluginCssAssets = CSS_ASSETS
export const pluginFontAssets = FONT_ASSETS

// Asset metadata
export const ASSETS_METADATA = {
  generatedAt: '2025-12-22T13:49:58.681Z',
  cssCount: 4,
  fontCount: 1
}
