/**
 * GlobalAssets - Dynamic CSS and Font Asset Injection
 * 
 * This component handles injecting all required CSS and font assets
 * for the widget system. It combines:
 * 1. Core assets (always needed)
 * 2. Plugin assets (from installed widget plugins)
 * 
 * Usage: Include <GlobalAssets /> at the root of your component tree
 */

import React, { useEffect, useState } from 'react'

// ============================================================================
// Types
// ============================================================================

interface AssetConfig {
  css: string[]
  fonts: string[]
}

// ============================================================================
// Core Assets (always included)
// ============================================================================

const CORE_ASSETS: AssetConfig = {
  css: [
    // Tabulator CSS for table widget
    'https://unpkg.com/tabulator-tables@6.3.1/dist/css/tabulator.min.css',
    // FullCalendar CSS for calendar widget
    'https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.19/main.min.css',
    'https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@6.1.19/main.min.css',
    'https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@6.1.19/main.min.css'
  ],
  fonts: [
    // Inter font for consistent typography
    'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap'
  ]
}

// ============================================================================
// Plugin Assets Integration
// ============================================================================

// Try to import generated plugin assets if available
let PLUGIN_ASSETS: AssetConfig = { css: [], fonts: [] }

try {
  // This will be generated by build-plugins.ts
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const generated = require('./GlobalAssets.generated')
  if (generated.pluginCssAssets) {
    PLUGIN_ASSETS.css = generated.pluginCssAssets
  }
  if (generated.pluginFontAssets) {
    PLUGIN_ASSETS.fonts = generated.pluginFontAssets
  }
} catch {
  // No generated assets yet - this is fine during initial setup
  console.debug('GlobalAssets: No generated plugin assets found')
}

// ============================================================================
// Merged Assets
// ============================================================================

function getMergedAssets(): AssetConfig {
  // Combine and deduplicate assets
  const allCss = [...new Set([...CORE_ASSETS.css, ...PLUGIN_ASSETS.css])]
  const allFonts = [...new Set([...CORE_ASSETS.fonts, ...PLUGIN_ASSETS.fonts])]
  
  return { css: allCss, fonts: allFonts }
}

// ============================================================================
// Asset Loading State Hook
// ============================================================================

interface AssetLoadState {
  loaded: boolean
  errors: string[]
}

function useAssetLoader(assets: AssetConfig): AssetLoadState {
  const [state, setState] = useState<AssetLoadState>({
    loaded: false,
    errors: []
  })
  
  useEffect(() => {
    const errors: string[] = []
    let loadedCount = 0
    const totalAssets = assets.css.length + assets.fonts.length
    
    if (totalAssets === 0) {
      setState({ loaded: true, errors: [] })
      return
    }
    
    const checkAllLoaded = () => {
      loadedCount++
      if (loadedCount >= totalAssets) {
        setState({ loaded: true, errors })
      }
    }
    
    // Track loaded stylesheets to avoid duplicates
    const existingLinks = new Set(
      Array.from(document.querySelectorAll('link[rel="stylesheet"]'))
        .map(link => (link as HTMLLinkElement).href)
    )
    
    // Load CSS assets
    assets.css.forEach(cssUrl => {
      if (existingLinks.has(cssUrl)) {
        checkAllLoaded()
        return
      }
      
      const link = document.createElement('link')
      link.rel = 'stylesheet'
      link.href = cssUrl
      link.onload = checkAllLoaded
      link.onerror = () => {
        errors.push(`Failed to load CSS: ${cssUrl}`)
        checkAllLoaded()
      }
      document.head.appendChild(link)
    })
    
    // Load font assets
    assets.fonts.forEach(fontUrl => {
      if (existingLinks.has(fontUrl)) {
        checkAllLoaded()
        return
      }
      
      const link = document.createElement('link')
      link.rel = 'stylesheet'
      link.href = fontUrl
      link.onload = checkAllLoaded
      link.onerror = () => {
        errors.push(`Failed to load font: ${fontUrl}`)
        checkAllLoaded()
      }
      document.head.appendChild(link)
    })
  }, [assets])
  
  return state
}

// ============================================================================
// GlobalAssets Component
// ============================================================================

interface GlobalAssetsProps {
  /** Additional CSS URLs to load */
  additionalCss?: string[]
  /** Additional font URLs to load */
  additionalFonts?: string[]
  /** Callback when all assets are loaded */
  onLoad?: () => void
  /** Callback if any assets fail to load */
  onError?: (errors: string[]) => void
}

/**
 * GlobalAssets Component
 * 
 * Renders all required CSS and font links for the widget system.
 * This is a declarative approach that works well with React's rendering model.
 */
export const GlobalAssets: React.FC<GlobalAssetsProps> = ({
  additionalCss = [],
  additionalFonts = [],
  onLoad,
  onError
}) => {
  const mergedAssets = getMergedAssets()
  
  // Combine with additional assets
  const allAssets: AssetConfig = {
    css: [...new Set([...mergedAssets.css, ...additionalCss])],
    fonts: [...new Set([...mergedAssets.fonts, ...additionalFonts])]
  }
  
  const { loaded, errors } = useAssetLoader(allAssets)
  
  // Fire callbacks when loading completes
  useEffect(() => {
    if (loaded) {
      if (errors.length > 0 && onError) {
        onError(errors)
      } else if (onLoad) {
        onLoad()
      }
    }
  }, [loaded, errors, onLoad, onError])
  
  // Render link tags declaratively (for SSR compatibility and React DevTools visibility)
  return (
    <>
      {/* Font preconnects for faster loading */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      
      {/* Font stylesheets */}
      {allAssets.fonts.map((font, index) => (
        <link key={`font-${index}`} href={font} rel="stylesheet" />
      ))}
      
      {/* CSS stylesheets */}
      {allAssets.css.map((css, index) => (
        <link key={`css-${index}`} rel="stylesheet" href={css} />
      ))}
    </>
  )
}

// ============================================================================
// Exports
// ============================================================================

export { CORE_ASSETS, PLUGIN_ASSETS, getMergedAssets }
export type { AssetConfig, GlobalAssetsProps }

