/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/build-plugins.ts
 * 
 * This file is regenerated every time plugins are built.
 * To add or remove widgets, edit retool-widget-plugins.json
 */

import { type FC } from 'react'

// Core widget imports (src/components/widgets/)
import { TextWidget, TextWidgetInstruction } from './TextWidget'

// External widget imports (src/components/widgets/external/)
import { CanvasWidget, CanvasWidgetInstruction } from './external/CanvasWidget'
import { ChartWidget, ChartWidgetInstruction } from './external/ChartWidget'

// NPM plugin imports (node_modules/)
// No npm plugins installed

// Widget instruction interface
interface WidgetInstruction {
  type: string
  instructions: string
  sourceDataModel: string | object
  hint?: string
}

// Widget configuration interface
interface GeneratedWidgetConfig {
  component: FC<any>
  instruction: WidgetInstruction
  enabled: boolean
  source: 'core' | 'external' | 'plugin'
  packageName?: string
}

// Generated widget registry
export const GENERATED_WIDGET_REGISTRY: Record<string, GeneratedWidgetConfig> = {
  text: {
    component: TextWidget,
    instruction: TextWidgetInstruction,
    enabled: true,
    source: 'core'
  },
  canvas: {
    component: CanvasWidget,
    instruction: CanvasWidgetInstruction,
    enabled: true,
    source: 'external'
  },
  chart: {
    component: ChartWidget,
    instruction: ChartWidgetInstruction,
    enabled: true,
    source: 'external'
  }
}

// Export list of all widget types
export const GENERATED_WIDGET_TYPES = Object.keys(GENERATED_WIDGET_REGISTRY)

// Export plugin metadata
export const PLUGIN_METADATA = {
  generatedAt: '2025-12-22T13:49:58.679Z',
  coreWidgets: ["text"],
  externalWidgets: ["canvas","chart"],
  npmPlugins: [],
  configuredExternal: ["canvas","chart"],
  externalAll: false
}
